app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss

set the colors and modify the bootstrap variables

set the base color

---

app/controllers/pets_controller.rb
app/views/pets/new.html.erb

finished backend implementation for creating a new pet (pets/new) 
frontend is pending until Roberto finishes standardizing the CSS.

Modify pets new create

---

app/views/pets/show.html.erb

Didn´t change the style for now, just the standard version Yuri told us to do.

will add more style later

---

app/controllers/appointments_controller.rb
app/controllers/clinics_controller.rb
app/models/clinic.rb
app/models/tutor.rb
app/models/vet.rb
app/views/clinics/show.html.erb
config/routes.rb
test/controllers/appointments_controller_test.rb

1. created appointment controller
2. created clinics/:id page 
the clinic can see all appointments they have.
3. frontend for clinics/:id is pending

Appointment controller

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/clinics_controller.rb
app/models/appointment.rb
app/views/clinics/show.html.erb

1. implemented clinic show page
the link path is pending. Still we don't have a link to jump to the edit vet and vet profile.
and the photo is pending too.
2. created the button CSS file, to standardize the text color

Clinics show

---

app/controllers/vets_controller.rb
app/views/clinics/show.html.erb

fix the link path to see vet profile and create a new vet
The link path to see the vet profile is pending until we finish the vet profile page.

fix the link path

---

app/controllers/clinics_controller.rb
app/controllers/vets_controller.rb
app/views/clinics/_edit_clinic.html.erb
app/views/clinics/show.html.erb
app/views/vets/_edit_vet.html.erb
app/views/vets/show.html.erb
config/routes.rb

Implemented backend for clinic and vet.
for Vet: 
- The user(clinic) can delete vet
- The vet can edit their information (frontend is pending, the form is commented out for now )
for clinic: 
-The clinic can edit their information  (frontend is pending, the form is commented out for now)

backend for edit&delete vet and edit clinic

---

app/controllers/appointments_controller.rb
app/controllers/pets_controller.rb
app/controllers/reviews_controller.rb
app/models/appointment.rb
app/models/review.rb
app/views/clinics/show.html.erb
app/views/pets/show.html.erb
app/views/reviews/_form.html.erb
app/views/reviews/new.html.erb
config/routes.rb
db/migrate/20240313155553_remove_vet_rating_from_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb

added reviews in pet show page
can read reviews in the clinic appointments

reviews done

---

app/controllers/clinics_controller.rb
app/views/clinics/_clinic_apo.html.erb
app/views/clinics/show.html.erb

I separated older appointments and upcoming appointments

implemented appointment section

---

app/controllers/clinics_controller.rb
app/controllers/vets_controller.rb

small fix for vet & clinic controller

fix vet and clinic controller

---

app/controllers/pets_controller.rb
app/controllers/tutors_controller.rb
app/views/pets/_edit_pet.html.erb
app/views/pets/show.html.erb
app/views/tutors/_edit_tutor.html.erb
app/views/tutors/show.html.erb
config/routes.rb

Implemented backend for tutor and pet.
for Pet:
The user(tutor) can delete the pet
The user can edit pet information (frontend is pending, the form is commented out for now )
for Tutor:
-The tutor can edit their information (frontend is pending, the form is commented out for now)

backend for edit&delete pet and edit tutor

---

app/views/clinics/show.html.erb
app/views/pets/show.html.erb
app/views/tutors/show.html.erb
app/views/vets/show.html.erb
config/routes.rb

commented out the Vet, Pet, Tutor, and Clinic page for the edit button.
Ideally, we hide the edit form with JS, e.g. when the user clicks the " edit " button and then the edit form appears.
and fixed the routes file, since there was a conflict between 2 merge requests that I sent yesterday, and the corresponding routes for vet were deleted.

Comment out edit delete btn

---

app/controllers/clinics_controller.rb

fixed the search bar for appointments

fix search bar for appointment

---

app/controllers/clinics_controller.rb
app/policies/clinic_policy.rb
app/views/clinics/_edit_clinic.html.erb
app/views/clinics/show.html.erb

fix edit btn and create a new vet

Fix edit and new btn for clinic

---

app/assets/stylesheets/components/_card.scss
app/views/clinics/_clinic_apo.html.erb
app/views/clinics/show.html.erb

The vets card and appointments will apear side by side.
Changed the create new vet button to the bottom of the list of vets.

Changed the style of vets card and appointments

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/views/clinics/_clinic_apo.html.erb
app/views/clinics/_edit_clinic.html.erb
app/views/clinics/show.html.erb
app/views/tutors/_edit_tutor.html.erb
app/views/tutors/show.html.erb

Add cards profiles new design, hide button from clinic and cards aren´t clicable anymore"

Changed clinics profile, tutors profile, and add some style at the pages

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_link.scss
app/views/tutors/_edit_tutor.html.erb
app/views/tutors/show.html.erb

Add style and changed the buttons place on tutors page.

Fixed the edit tutors button and the delete pet button.

---

app/assets/stylesheets/config/_colors.scss

fixed the background color as the previous color.

fixed the background color

---

app/models/pet.rb
app/views/pets/_form.html.erb

Add the choice of species to the user.

add species dropdown

---

app/assets/stylesheets/components/_form_modal.scss
app/assets/stylesheets/components/_index.scss

You should see the forms create a pet and new appointments rounded and title centralized.

changed forms style to rounded and centralized title

---

app/controllers/reviews_controller.rb

fixed review redirect path

---

app/views/tutors/_edit_tutor.html.erb

changed the button text

---

app/views/appointments/_form.html.erb

fixed new appointment modal 
from "datetime" -> "choose a date"

fixed new appointment modal

---

app/assets/stylesheets/components/_banner.scss
app/views/clinics/show.html.erb

Changed clinic card and footer margin
